version: '3.4'

services:
  mysql-development:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: Rrs1748?
      MYSQL_DATABASE: coffee-shop
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"